<#import "/$/modelbase.ftl" as modelbase>
<#import "/$/appbase.ftl" as appbase>
<#assign widget = properties>
<@appbase.print_source_code_js snippet="declare" widget=widget indent=2 />
<#--<#if widgetType == '编辑表单'>-->
<#--<@appbase.print_js_declare_formlayout widget=properties indent=2 />-->
<#--<#elseif widgetType == '花式表单'>-->
<#--<@appbase.print_js_declare_styledform widget=properties indent=2 />-->
<#--<#elseif widgetType == '只读表单'>-->
<#--<@appbase.print_js_declare_readonlyform widget=properties indent=2 />-->
<#--<#elseif widgetType == '传统列表'>-->
<#--<@appbase.print_js_declare_listview widget=properties indent=2 />-->
<#--<#elseif widgetType == '滚动导航'>-->
<#--<@appbase.print_js_declare_cyclenavigator widget=properties indent=2 />-->
<#--<#elseif widgetType == '滑动导航'>-->
<#--<@appbase.print_js_declare_scrollnavigator widget=properties indent=2 />-->
<#--<#elseif widgetType == '页签导航'>-->
<#--<@appbase.print_js_declare_tabnavigator widget=properties indent=2 />-->
<#--<#elseif widgetType == '向导导航'>-->
<#--<@appbase.print_js_declare_wizard widget=properties indent=2 />-->
<#--<#elseif widgetType == '日历导航'>-->
<#--<@appbase.print_js_declare_calendar widget=properties indent=2 />-->
<#--<#elseif widgetType == '统计图表'>-->
<#--<@appbase.print_js_declare_chart widget=properties indent=2 />-->
<#--<#elseif widgetType == 'Timeline'>-->
<#--<@appbase.print_js_declare_timeline managedObject=managedObject indent=2 />-->
<#--<#elseif widgetType == 'Tabs'>-->
<#--<@appbase.print_js_declare_tabs widget=properties indent=2 />-->
<#--</#if>-->