<#import "/$/modelbase.ftl" as modelbase>
<#import "/$/appbase.ftl" as appbase>
<#assign widget = properties>
<@appbase.print_source_code_html snippet="declare" widget=widget indent=0 />
<#--<#if properties.widgetType == '滚动导航'>-->
<#--<@appbase.print_html_declare_cyclenavigator widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '滑动导航'>-->
<#--<@appbase.print_html_declare_scrollnavigator widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '按钮导航'>-->
<#--<@appbase.print_html_declare_gridnavigator widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '栏位导航'>-->
<#--<@appbase.print_html_declare_columnnavigator widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '列表导航'>-->
<#--<@appbase.print_html_declare_listnavigator widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '页签导航'>-->
<#--<@appbase.print_html_declare_tabnavigator widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '分组导航'>-->
<#--<@appbase.print_html_declare_groupnavigator widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '编辑表单'>-->
<#--<@appbase.print_html_declare_formlayout widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '花式表单'>-->
<#--<@appbase.print_html_declare_styledform widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '只读表单'>-->
<#--<@appbase.print_html_declare_readonlyform widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '只读表单'>-->
<#--&lt;#&ndash; 什么都不需要，容器页面在前端添加 &ndash;&gt;-->
<#--<#elseif properties.widgetType == '通知公告'>-->
<#--<@appbase.print_html_declare_notification widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '主题标题'>-->
<#--<@appbase.print_html_declare_themetitle widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '主题肖像'>-->
<#--<@appbase.print_html_declare_avatar widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '搜索输入'>-->
<#--<@appbase.print_html_declare_searchbox widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '文本按钮'>-->
<#--<@appbase.print_html_declare_textbuttons widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '静态图片'>-->
<#--<@appbase.print_html_declare_staticimage widget=properties indent=0 />-->
<#--<#elseif properties.widgetType == '空白卡片'>-->
<#--<@appbase.print_html_declare_blankcard widget=properties indent=0 />-->
<#--</#if>-->